services:
  clue-fca-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: clue-fca-app
    ports:
      - '3000:80'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - clue-fca-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.clue-fca.rule=Host(`localhost`)'
      - 'traefik.http.services.clue-fca.loadbalancer.server.port=80'

networks:
  clue-fca-network:
    driver: bridge

volumes:
  clue-fca-data:
    driver: local
