import { Challenge, Unit, User } from '@/types'
import { addDays } from 'date-fns'

export const mockChallenges: Challenge[] = [
  {
    id: '1',
    name: '30-Day Step Challenge',
    description: 'Walk 10,000 steps daily for 30 days. Join friends and track your progress!',
    type: 'steps',
    goal: 10000,
    unit: Unit.STEPS,
    duration: 30,
    startDate: new Date(),
    endDate: addDays(new Date(), 30),
    participants: ['user1', 'user2', 'user3', 'user4', 'user5', 'user6', 'user7'],
    creator: 'FitnessApp',
    isActive: true,
    imageUrl: '🚶',
  },
  {
    id: '2',
    name: 'Marathon Prep',
    description: 'Run 5 miles daily building up to marathon distance',
    type: 'distance',
    goal: 5,
    unit: Unit.MILES,
    duration: 21,
    startDate: new Date(),
    endDate: addDays(new Date(), 21),
    participants: ['user2', 'user4', 'user6', 'user8', 'user10'],
    creator: 'RunClub',
    isActive: true,
    imageUrl: '🏃',
  },
  {
    id: '3',
    name: 'Calorie Crusher',
    description: 'Burn 500 calories daily through any activity',
    type: 'calories',
    goal: 500,
    unit: Unit.CALORIES,
    duration: 14,
    startDate: new Date(),
    endDate: addDays(new Date(), 14),
    participants: ['user1', 'user3', 'user5', 'user7', 'user9', 'user10'],
    creator: 'FitnessGuru',
    isActive: true,
    imageUrl: '🔥',
  },
  {
    id: '4',
    name: 'Weight Loss Journey',
    description: 'Lose 1 pound per week in a supportive community',
    type: 'weight_loss',
    goal: 1,
    unit: Unit.POUNDS,
    duration: 28,
    startDate: new Date(),
    endDate: addDays(new Date(), 28),
    participants: ['user3', 'user6', 'user9'],
    creator: 'HealthCoach',
    isActive: true,
    imageUrl: '⚖️',
  },
  {
    id: '5',
    name: 'Workout Time',
    description: 'Workout for 30 minutes daily for 21 days',
    type: 'workout_time',
    goal: 30,
    unit: Unit.MINUTES,
    duration: 21,
    startDate: new Date(),
    endDate: addDays(new Date(), 21),
    participants: ['user1', 'user2', 'user5', 'user6', 'user8', 'user9', 'user10'],
    creator: 'FitnessApp',
    isActive: true,
    imageUrl: '💪',
  },
]

export const mockUsers: User[] = [
  { id: 'user1', name: 'Alex Johnson', email: 'alex@example.com', avatar: '👨‍💼', joinedAt: new Date() },
  { id: 'user2', name: 'Sarah Chen', email: 'sarah@example.com', avatar: '👩‍🦳', joinedAt: new Date() },
  { id: 'user3', name: 'Mike Rodriguez', email: 'mike@example.com', avatar: '👨‍🎓', joinedAt: new Date() },
  { id: 'user4', name: 'Emma Davis', email: 'emma@example.com', avatar: '👩‍💻', joinedAt: new Date() },
  { id: 'user5', name: 'David Wilson', email: 'david@example.com', avatar: '👨‍🔧', joinedAt: new Date() },
  { id: 'user6', name: 'John Doe', email: 'john@example.com', avatar: '👨‍💼', joinedAt: new Date() },
  { id: 'user7', name: 'Jane Smith', email: 'jane@example.com', avatar: '👩‍💼', joinedAt: new Date() },
  { id: 'user8', name: 'Michael Brown', email: 'michael@example.com', avatar: '👨‍💼', joinedAt: new Date() },
  { id: 'user9', name: 'Emily Johnson', email: 'emily@example.com', avatar: '👩‍💼', joinedAt: new Date() },
  { id: 'user10', name: 'Robert Lee', email: 'robert@example.com', avatar: '👨‍💼', joinedAt: new Date() },
]
